### ISSUE TITLE
.

### ISSUE THREAD

**Issue by graysuit** [cnlohr/rawdrawandroidexample#2]

**Comment by cnlohr** [comment]
ColorChord currently has an android build, and it is also on the Android store, so you can play with it there.  Otherwise, you are going to need to build this example app and work form there.

**Comment by graysuit** [comment]
This one right ?
https://play.google.com/store/apps/details?id=org.cnlohr.colorchord
Thank you so much for support.
I will close issue after testing it and publicizing the results here.

**Comment by graysuit** [comment]
https://play.google.com/store/apps/details?id=org.cnlohr.colorchord&reviewId=gp%3AAOqpTOGQnaVqJNyRzvb0mhXcm4I3SUmpMb8WRW53x7k8jbiSmv0B13aD9UAWGuv_86KVgB6iTE2GQCENK9OnRg

I thought its just a lie that **rawdrawandroid** is 100% native.
I thought it will load *.so file from classes.dex and call it native like xamarin,android_studio,basic4android does.
But I am very impressed to see following truths
-its 100% native using C work
-Can't de-compile (other non native do decompiled)
-Entirely loaded by native dynamic libraries *.so
-FileSize is about in some kb's
-Run directly into device without vm (which java, C# can't do) 
-Speed is ultra fast. I will recommend it for controlling low level device parts e.g 
-**res** contains 2 folders **mipmap**(for icon) and xml(not sure about that)


Some things are traditional and remain same
-AndroidManifest.xml for permissions tasks
-META-INF contains signature 
-lib contains native *.so files
-assets contain assets.txt
